import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { SectionHeading } from "@/components/section-heading";
import { FileBarChart2, Download } from "lucide-react";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports · WorldCupIQ AI" },
      { name: "description", content: "Executive briefs, trend reports and post-match analytics generated by the reporting agent." },
    ],
  }),
  component: ReportsPage,
});

const reports = [
  { title: "Match-day executive brief · Group Stage 12", ago: "10 min", size: "4.2 MB" },
  { title: "Weekly transportation trend report", ago: "yesterday", size: "1.7 MB" },
  { title: "Accessibility SLA compliance", ago: "2 days", size: "820 KB" },
  { title: "Emergency response drill after-action", ago: "1 week", size: "3.4 MB" },
];

function ReportsPage() {
  return (
    <AppShell title="Reports Center" subtitle="Generated briefs, trend reports and after-action analytics">
      <SectionHeading eyebrow="Library" title="Recent reports" />
      <ul className="space-y-2">
        {reports.map((r, i) => (
          <li key={i} className="glass flex flex-wrap items-center gap-3 rounded-xl p-4">
            <FileBarChart2 className="h-5 w-5 text-primary" aria-hidden />
            <div className="flex-1 min-w-0">
              <div className="font-medium">{r.title}</div>
              <div className="text-xs text-muted-foreground">Generated {r.ago} · {r.size}</div>
            </div>
            <button className="inline-flex items-center gap-1.5 rounded-md border border-border/70 px-3 py-1.5 text-sm hover:bg-background/60">
              <Download className="h-4 w-4" aria-hidden /> Download
            </button>
          </li>
        ))}
      </ul>
    </AppShell>
  );
}